---
title: "2015-10-28 - Place and Oral History"
date: 2015-10-28
tags: [space, place, oral history, conference, Western History Association]
categories: [Essays]
---

> Notes from the Western History Association Conference, Oct. 28, 2015.

Place and Oral History in the American West

## Leisl

Peter Jackson

Don Mitchell

Tapestry to make the world legible

Individuals and the way they experiment the past in place.

Active engagement in place making

Issues and ideas of place. Important to environmental history.

Impact of activity on their homes

Keith Basso, stories embedded in place

Changing environment -> experience of place

## Alicia Barber

- a "place as crossroads"
- <http://www.aliciambarber.com>
- <http://4thprater.onlinenevada.org>

## Shanna M. Farrell

West Coast cocktails oral history project

Formed a group of advisors

Dale DeGruff -> changes the face of modern cocktails

Rupf, Wondrich

Geography central to the project

## Greg Smoak

Great Salt Lake

Jared Farmer, book on Great Salt Lake

Place is formed by lived experience. Moves beyond space, embeds meaning. Oral history helps real this

Interviewing for place

- record lived experience
- brief biography
- general questions about the place
- focus on specific knowledge

## QA

Outcomes? (Web, preservation, etc)

Funding? Align with external goals, sense of urgency, anniversaries.
