---
title: "basso1996places"
date: 2016-02-01
tags: [place, Apache, landscape, reading notes]
categories: [Readings]
---

p. xiii: "As normally experienced, sense of place quite simply *is*, as natural and straightforward as our fondness for certain colors and culinary tastes, and the thought that it might be complicated, or even very interesting, seldom crosses our minds. Until, as sometimes happens, we are deprived of these attachments and find ourselves adrift, literally *dislocated*, in unfamiliar surroundings we do not comprehend and care for even less."

p. xiii: Place can be subtle, present in the absence of smell in the air or not enough visible sky. "It is then we come to see that attachments to places may be nothing less than profound, and that when these attachments are threatened we may feel threatened as well. Places, we realize, are as much a part of us as we are of them."

p. xiv: "senses of place also partake of cultures, of shared bodies of 'local knowledge' (the phrase is Clifford Geertz's) with which persons and whole communities render their places meaningful and endow them with social importance."

p. xv:

> Apache constructions of place reach deeply into other cultural spheres, including conceptions of wisdom, notions of morality, politeness and tact in forms of spoken discourse, and certain conventional ways of imagining and interpreting the Apache tribal past.

p. xvi: "People, not cultures, sense places"

p. 5: "place-making is a universal tool of the historical imagination" --- place-making involves "acts of remembering and imagining which inform each other in complex ways." Basso calls this *place-world* (p. 6), "wherein portions of the past are brought into being."

p. 6: Place-making "is a way of constructing history itself"

p. 7: "what people make of their places is closely connected to what they make of themselves as members of society and inhabitants of the earth"

p. 7: "If place-making is a way of constructing the past, a venerable means of *doing* human history, it is also a way of constructing social traditions and, in the process, personal and social identities. We *are*, in a sense, the place-worlds we imagine."

p. 8--9: The book emerged from a project on Cibecue land on the Fort Apache Indian Reservation, endorsed by the White Mountain Apache Tribal Council.

p. 13: "place-names can offer evidence of changes in the landscape, showing clearly that certain localities do not present the appearance they did in former times."

p. 28: "the country takes on a different cast, a density of meaning---and with it a formidable strength---it did not have before. Here, there, and over there, I see, are places which proclaim by their presence and their names both the imminence of chaos and the preventive wisdom of moral norms."

p. 28: "commemorative place-names . . . marking the site of some sad or tragic event from which valuable lessons can be readily drawn and take fast to heart."

p. 40: "Western Apache storytelling which holds that oral narratives have the power to establish enduring bonds between individuals and features of the natural landscape."

p. 41: "Ultimately, it [storytelling] is a model of how two symbolic resources---language and the land---are manipulated by Apaches to promote compliance with standards for acceptable social behavior and the moral values that support them."

p. 73: Ethnographers likely notice three distinct ways communities approach local landscapes:

  1. observe the landscape
  2. use the landscape
  3. communicate about the landscape

p. 74: "whenever the members of a community speak about their landscape---whenever they name it, or classify it, or tell stories about it---they unthinkingly represent it in ways that are compatible with shared understandings of how, in the fullest sense, they know themselves to occupy it."

p. 75: "landscapes and the places that fill them become tools for the imagination"

p. 75: "men and women learn to *appropriate* their landscapes, to think and act 'with' them as well as about and upon them, and to weave them with spoken words into the very foundations of social life."

p. 75: "geographical landscapes are never culturally vacant. The ethnographic challenge is to fathom what it is that a particular landscape, filled to brimming with past and present significance, can be called upon to 'say,' and what, through the saying, it can be called upon to 'do.'"

p. 102: "Inhabitants *of* their landscape, the Western Apache are thus inhabited *by* it as well, and in the timeless depth of that abiding reciprocity, the people and their landscape are virtually as one."

p. 106: "anthropologists have paid scant attention to one of the most basic dimensions of human experience---that close companion of heart and mind, often subdued yet potentially overwhelming, that is known as *sense of place*."

p. 106: Drawing on Martin Heidegger (1977), proposes "the concept of *dwelling* assigns importance to the forms of consciousness with which individuals perceive and apprehend geographical space."

p. 107: "When places are actively sensed, the physical landscape becomes wedded to the landscape of the mind, to the roving imagination, and where the latter may lead is anybody's guess."

p. 109: "relationships to places are lived most often in the company of other people, and it is on these communal occasions---when places are sensed *together*---that native views of the physical world become accessible to strangers."

p. 110: "places and their meanings are continually woven into the fabric of social life, anchoring it to features of the landscape and blanketing it with layers of significance that few can fail to appreciate."

p. 111: "Places and their sensings deserve our close attention."

p. 143: "sense of place---or, as I would prefer to say, *sensing* of place---is a form of cultural activity."

p. 144: "But that each of us should be drawn to particular pieces of territory, and for reasons we take to be relatively uncomplicated, is radically expectable. A sense of place, everyone presumes, is everyone's possession."

p. 145: "Everything, or almost everything, hinges on the particulars, and because it does, ethnography is essential."

p. 145: 

> As vibrantly felt as it is vividly imagined, sense of place asserts itself at
> varying levels of mental and emotional intensity. Whether it is lived in
> memory or experienced on the spot, the strength of its impact is commensurate
> with the richness of its contents, with the range and diversity of symbolic
> associations that swim within its reach and move it on its course.

p. 146: "sense of place roots individuals in the social and cultural soils from which they have sprung together"

p. 148: "sense of place rests its case on the unexamined premise that being from *somewhere* is always preferable to being from *nowhere*. All of us, it asserts, are generally better off with a place to call our own. Places, it reminds us, are really very good."
