---
title: "HIST 2990: Digital Humanities"
date: 2017-06-21
tags: [digital history, digital humanities]
categories: [Teaching]
---

## Projects

Focusing the course around the history of Omaha. I'm considering Curatescape again, like I had for [the Stanford course](http://notebook.jasonheppler.org/hist205f-syllabus-revisions/).

## Readings

-   Neal Stephenson, *[In the Beginning Was the Command Line](http://www.cryptonomicon.com/beginning.html)* (Avon, 1999).
-   Paul Ford, "[What is Code](http://www.bloomberg.com/graphics/2015-paul-ford-what-is-code/)"
-   Scott Weingart, "['Digital History' Can Never Be New](http://scottbot.net/digital-history-can-never-be-new/)"
-   Fred Gibbs, "[New Forms of History: Critiquing Data and Its Representations](http://tah.oah.org/february-2016/new-forms-of-history-critiquing-data-and-its-representations/)" *The American Historian*
-   Lara Putnam, "The Transnational and the Text-Searchable: Digitized Sources and the Shadows They Cast" *JAH*
-   Andrew Hurley, "[Chasing the Frontiers of Digital Technology](http://tph.ucpress.edu/content/38/1/69.full.pdf+html)" *The Public Historian* vol. 38 no. 1 (February 2016): 69--88.
-   Larsen, Lawrence, et al. *Upstream Metropolis: An Urban Biography of Omaha & Council Bluffs* (Lincoln: University of Nebraska Press, 2007).
-   Larson, Lawrence, and Barbara J. Cottrell. *The Gate City: A History of Omaha* (Lincoln: University of Nebraska Press, 1982).
-   Menard, Orville D. *River City Empire: Tom Dennison's Omaha* (Lincoln: University of Nebraska Press, 1989).
