---
title: "HIST205F syllabus revisions"
date: 2016-04-29
tags: [digital history, digital humanities]
categories: [Teaching]
---

## Projects

-   Building exhibits on Curatescape.
    -   Getting students into Stanford Archives; a spatial history of the university
    -   [Google Doc on compiling project and topic ideas](https://docs.google.com/document/d/1FJT8CC8aEUpnrQpmBwM9KByhjF6mLsekgTtoPkLZrVM/edit?usp=sharing)

## Readings

-   Neal Stephenson, *[In the Beginning Was the Command Line](http://www.cryptonomicon.com/beginning.html)* (Avon, 1999).
-   Paul Ford, "[What is Code](http://www.bloomberg.com/graphics/2015-paul-ford-what-is-code/)"
-   Scott Weingart, "['Digital History' Can Never Be New](http://scottbot.net/digital-history-can-never-be-new/)"
-   Fred Gibbs, "[New Forms of History: Critiquing Data and Its Representations](http://tah.oah.org/february-2016/new-forms-of-history-critiquing-data-and-its-representations/)" *The American Historian*
-   Lara Putnam, "The Transnational and the Text-Searchable: Digitized Sources and the Shadows They Cast" *JAH*
-   Andrew Hurley, "[Chasing the Frontiers of Digital Technology](http://tph.ucpress.edu/content/38/1/69.full.pdf+html)" *The Public Historian* vol. 38 no. 1 (February 2016): 69--88.
-   Margaret O’Mara, *Cities of Knowledge: Cold War Science and the Search for the Next Silicon Valley*. Princeton University Press, 2004.
-   John M. Findlay. *Magic Lands: Western Cityscapes and American Culture After 1940*. University of California Press, 1992.
-   Roger Lotchin. *Fortress California, 1910-1961: From Warfare to Welfare*. University of Illinois Press, 2002.
-   Cecilia M. Tsu. *Garden of the World: Asian Immigrants and the Making of Agriculture in California’s Santa Clara Valley*. Oxford University Press, 2013.
-   Richard Walker. *The Country in the City: The Greening of the San Francisco Bay Area*. University of Washington Press, 2007.
-   Stephen J. Pitti. *The Devil in Silicon Valley: Northern California, Race, and Mexican Americans*. Princeton University Press, 2003.
-   Rebecca Lowen. *Creating the Cold War University: The Transformation of Stanford*. University of California Press, 1997.
-   Herbert G. Ruffin II. *Uninvited Neighbors: African Americans in Silicon Valley, 1769-1990*. University of Oklahoma Press, 2014.

Look back on the [spatial history list](/spatial-history-annotated-bibliography/) and see what readings would be a good fit. Also, what readings can I pull in about public history? About digital exhibits and digital archives?
