---
title: "Reading List - North American West"
date: 2016-02-02
tags: [American West]
categories: [Readings]
---

Jason A. Heppler
University of Nebraska -- Department of History  
Readings List -- U.S. West  
Advisor: Prof. Doug Seefeldt

## 1. Defining the West / Frontier

Cronon, William. *Under an Open Sky: Rethinking America's Western Past*. New York: Norton, 1994.

Etulain, Richard W. *Re-Imagining the Modern American West: A Century of Fiction, History, and Art* (1996).

Limerick, Patricia, Clyde Milner, and Charles Rankin. *Trails: Toward a New Western History*. Lawrence: University Press of Kansas, 1991.

Limerick, Patricia. *The Legacy of Conquest: The Unbroken Past of the American West*. New York: Norton, 1987.

Milner II, Clyde A., ed. *A New Significance: Re-envisioning the History of the American West* (1996).

Milner II, Clyde A., Carol A. O'Connor, and Martha Sandweiss, eds. *The Oxford History of the American West* (1994).

Nash, Gerald. *Creating the West: Historical Interpretations, 1890-1990* (1991).

Nash, Gerald and Richard W. Etulain, eds. *Researching Western History: Topics in the Twentieth Century* (1997).

------. *The Twentieth-Century West: Historical Interpretations* (1989).

Prown, Jules David, ed. *Discovered Lands, Invented Pasts: Transforming Visions of the American West* (1992).

Turner, Frederick Jackson. *Rereading Frederick Jackson Turner* [with commentary by John Mack Faragher] (1994).

White, Richard. *"It's Your Misfortune and None of My Own"*. 1991.

Wrobel, David. *The End of American Exceptionalism: Frontier Anxiety from the Old West to the New Deal* (1993).

Wrobel, David M. and Michael Steiner, eds. *Many Wests: Place, Culture, & Regional Identity* (1997).

## 2. Mythic West

Hyde, Anne Farrar. *An American Vision: Far Western Landscape and National Culture, 1820-1920* (1990).

Mitchell, Lee Clark. *Witness to a Vanishing America: The Nineteenth-Century Response* (1981).

Prown, Jules David, ed. *Discovered Lands, Invented Pasts: Transforming Visions of the American West* (1992).

Slotkin, Richard. *The Fatal Environment: The Myth of the Frontier in the Age of Industrialization* (1998)

Slotkin, Richard. *Gunfighter Nation: The Myth of the Frontier in Twentieth-Century America*. Norman: University of Oklahoma Press, 1998.

Smith, Henry. *Virgin Land: The American West as Symbol and Myth*. Harvard, 2007.

Smith, Sherry. *The View from Officers’ Row: Army Perceptions of Western Indians* (1991)

Warren, Louis S. *Buffalo Bill’s America: William Cody and the Wild West Show* (2005)

## 3. Native Empires & Encounters, Cooperation and Confrontations with Native Peoples

Blackhawk, Ned. *Violence over the Land: Indians and Empires in the Early American West*. Harvard University Press, 2008.

Brooks, James F. *Captives and Cousins: Slavery, Kinship, and Community in the Southwest Borderlands* (2002)

Calloway, Colin G. *One Vast Winter Count: The Native American West before Lewis and Clark* (2006)

DuVal, Kathleen. *The Native Ground: Indians and Colonists in the Heart of the Continent*. University of Pennsylvania Press, 2007.

Hamalainen, Pekka. *The Comanche Empire*.

Hurtado, Albert L. *Intimate Frontiers: Sex, Gender, and Culture in Old California* (1999)

Ostler, Jeffrey. *The Plains Sioux and U.S. Colonialism from Lewis and Clark to Wounded Knee* (2004)

Prucha, Francis Paul. *The Great Father: The United States Government and the American Indians* (1986)

Ronda, James. *Lewis and Clark among the Indians*. New York: Bison, 2002.

Wishart, David J. *An Unspeakable Sadness: The Dispossession of the Nebraska Indians* (1997)

Weber, David J. *The Mexican Frontier, 1821-1846: The American Southwest Under Mexico* (1982)

Weber, David J. *The Spanish Frontier in North America* (1994)

## 4. Expansion, War and Dependence

Carter, Sarah. *The Importance of Being Monogamous: Marriage and Nation Building in Western Canada to 1915* (2008)

DeLay, Brian. *War of a Thousand Deserts: Indian Raids and the U.S.-Mexican War* (2009)

Faragher, John Mack. *Women and Men on the Overland Trail* (1979, 2001)

 Goetzmann, William. *Exploration and Empire: The Explorer and the Scientist in the Winning of the American West* (1966).

Hoxie, Frederick E. *A Final Promise: The Campaign to Assimilate the Indians, 1880-1920* (2001)

Jacoby, Karl. *Shadows at Dawn: A Borderlands Massacre and the Violence of History* (2008)

Lamar, Howard R. *The Far Southwest, 1846-1912: A Territorial History*. Albuquerque: University of New Mexico Press, 2000.

May, Dean L. *Three Frontiers: Family, Land, and Society in the Americans West, 1850-1900* (1994)

Montoya, Maria. *Translating Property: The Maxwell Land Grant and the Conflict Over Land in the American West, 1840-1900* (2005)

Pascoe, Peggy. *Relations of Rescue: The Search for Female Moral Authority in the American West* (1990)

Robbins, William G. *Colony & Empire: The Capitalist Transformation of the American West* (1994).

Tate, Michael L. *The Frontier Army in the Settlement of the West* (2001).

Truett, Samuel. *Fugitive Landscapes: The Forgotten History of the U.S.-Mexico Borderlands* (2006).

Unrau, William E. *The Rise and Fall of Indian Country, 1825-1855* (2007).

Utley, Robert. *The Indian Frontier, 1846-1890*. University of New Mexico Press, [1984] 2003.

West, Elliot. *The Contested Plains: Indians, Goldseekers, and the Rush to Colorado* (2000)

White, Richard. *The Roots of Dependency: Subsistence, Environment, and Social Change among the Choctaws, Pawnees, and Navajos*. Lincoln: University of Nebraska Press, 1988.

Wooster, Robert. *The Military and United States Indian Policy, 1865-1903* (1998)

## 5. Environment, Natural Resources, and Conservation

Andrews, Thomas G. *Killing for Coal: America’s Deadliest Labor War* (2010)

Binnema, Theodore. *Common and Contested Ground: A Human and Environmental History of the Northwestern Plains* (2001)

Cronon, William. *Nature's Metropolis: Chicago and the Great West*. New York: Norton, 1991.

Evans, Sterling D. *Bound in Twine: The History and Ecology of the Henequen-Wheat Complex for Mexico and the American and Canadian Plains, 1880-1950* (2008)

Fiege, Mark. *Irrigated Eden: The Making of an Agricultural Landscape in the American West* (1999).

Harvey, Mark W. T. *A Symbol of Wilderness: Echo Park and the American Conservation Movement* (1994).

Hundley, Norris. *The Great Thirst: Californians and Water―A History*, Revised Edition ([1992], 2001).

Igler, David. Industrial Cowboys: Miller & Lux and the Transformation of the Far West, 1850-1920 (2005)

Isenberg, Andrew. *The Destruction of the Bison: An Environmental History,, 1750-1920*. Cambridge: Cambridge University Press, 2001.

Isenberg, Andrew C. *Mining California: An Ecological History* (2005)

Malone, Michael. *The Battle for Butte: Mining and Politics on the Northern Frontier, 1864-1906*. Seattle: University of Washington Press, 2006.

Merrill, Karin. *Public Lands and Political Meaning: Ranchers, the Government, and the Property Between Them*. Berkeley: University of California Press, 2002.

Pisani, Donald. *To Reclaim a Divided West: Water, Law, and Public Policy, 1848-1902*. Albuquerque: University of New Mexico Press, 1992.

 _______. *Water and the American Government: The Reclamation Bureau, National Water Policy, and the West, 1902-1935* (2002).

Righter, Robert W. *The Battle over Hetch Hetchy: America’s Most Controversial Damn and the Birth of Modern Environmentalism* (2005)

Russell, Sharman. *Kill the Cowboy: A Battle of Mythology in the New West*. Lincoln: University of Nebraska Press, 2001.

Spence, Mark David. *Dispossessing the Wilderness: Indian Removal and the Making of the National Parks* (2000)

Starrs, Paul. *Let the Cowboy Ride: Cattle Ranching in the American West*. Baltimore: John Hopkins University Press, 1998.

Stegner, Wallace. *Beyond the Hundredth Meridian: John Wesley Powell and the Second Opening of the West* (1962)

Webb, Walter. *The Great Plains*. Lincoln, 1981.

West, Elliott. *The Way to the West: Essays on the Central Plains* (1995).

White, Richard. *The Organic Machine: The Remaking of the Columbia River* (1995)

Wilkinson, Charles. *Crossing the Next Meridian: Land, Water, and the Future of the West*. Island Press, 1993.

Worster, Donald. *Rivers of Empire: Water, Aridity, and the Growth of the American West*. Oxford, 1992.

______. *Dust Bowl: The Southern Plains in the 1930s* (1979)

## 6. American West in the Twentieth Century

Abbott, Carl. *How Cities Won the West: Four Centuries of Urban Change in Western North America* (2008).

_______. *The Metropolitan Frontier: Cities in the Modern American West*. Tucson: University of Arizona Press, 1995.

Billington, David P. and Donald C. Jackson. *Big Dams of the New Deal Era: A Confluence of Engineering and Politics* (2006).

Decker, Peter R. *Old Fences, New Neighbors* (1998).

Findlay, John M. *Magic Lands: Western Cityscapes and American Culture After 1940*. Berkeley: University of California Press, 1993.

Garcia, Matt. *A World of Its Own: Race, Labor, and Citrus in the Making of Greater Los Angeles, 1900-1970* (2001)

Gomez, Arthur. *Quest for the Golden Circle: The Four Corners and the Metropolitan West, 1945-1970*. University of Kansas Press, 2000.

Egan, Timothy. *Lasso the Wind: Away to the New West*. Vintage, 1999.

Hurt, R. Douglas, ed. *The Rural West since World War II*. University Press of Kansas, 1998.

Hurt, R. Douglas. *The Great Plains during World War II*. Lincoln: University of Nebraska Press, 2008.

Johnson, Marilynn. *The Second Gold Rush: Oakland and the East Bay in World War II* (1996).

Lotchin, Roger W. *Fortress California 1910-1961: From Warfare to Welfare* (1992).

______. *The Bad City in the Good War: San Francisco, Los Angeles, Oakland, and San Diego*. Indiana University Press, 2003.

Lowitt, Richard. *The New Deal and the West*. Norman: University of Oklahoma Press, 1993.

Nash, Gerald D. *The American West Transformed: The Impact of the Second World War* (1985)

_______. *The Federal Landscape: An Economic History of the Twentieth-Century West*. Tucson: University of Arizona Press, 1999.

Ringholz, Raye. *Paradise Paved: The Challenge of Growth in the New West*. University of Utah Press, 1996.

Rothman, Hal. *Devil's Bargain: Tourism in the Twentieth-Century American West*. University Press of Kansas, 2000.

Stiles, Jim. *Brave New West: Morphing Moab at the Speed of Greed*. Tucson: University of Arizona Press, 2007.

Wiley, Peter and Robert Gottlieb. *Empires in the Sun: The Rise of the New American West*. University of Arizona Press, 1985.

## 7. Identity / Community

Benton-Cole, Catherine. *Borderline Americans: Racial Division and Labor War in the Arizona Borderlands* (2008)

Berglund, Barbara. *Making San Francisco American: Culture Frontiers in the Urban West, 1846-1890* (2007)

Broussard. *Black San Francisco: The Struggle for Racial Equality in the West, 1900-1954* (1993).

Daniels, Roger. *Prisoners Without Trial: Japanese Americans in World War II*, revised edition ([1993] 2004).

Fixico, Donald. *The Urban Indian Experience in America*. Albuquerque: University of New Mexico Press, 2000.

Gonzales, Deena. *Refusing the Favor: The Spanish-Mexican Women of Santa Fe, 1820-1880*.

Gregory, James N. *American Exodus: The Dust Bowl Migration and Okie Culture in California* (1989).

Gutierrez, David. *Walls and Mirrors: Mexican Americans, Mexican Immigrants, and the Politics of Ethnicity* (1995)

Hoxie, Frederick E. *Parading through History: The Making of the Crow Nation in America, 1805-1935* (1997)

Iverson, Peter. *When Indians Became Cowboys: Native Peoples and Cattle Ranching in the American West* (1994).

Leonard, Kevin Allen. *The Battle for Los Angeles: Racial Ideology and World War II*. Albuquerque: University of New Mexico Press, 2006.

Luckingham, Bradford. *Minorities in Phoenix: A Profile of Mexican American, Chinese American, and African American Communities, 1860-1992* (1994).

Markoff, John. *What the Dormouse Said: How the Sixties Counterculture Shaped the Personal Computer Industry* (2006).

Matsumoto, Valerie J. *Farming the Home Place: A Japanese American Community in California, 1919-1982* (1993).

Meeks, Eric. *Border Citizens: The Making of Indians, Mexicans, and Anglos in Arizona*. Austin: University of Texas Press, 2007.

Parman, Donald L. *Indians and the American West in the Twentieth Century* (1994)

Pitti, Stephen J. *The Devil in Silicon Valley: Northern California, Race, and Mexican Americans* (2003).

Ramos, Raúl. *Beyond the Alamo: Forging Mexican Ethnicity in San Antonio, 1821-1861*. Chapel Hill, 2008.

 Ruiz, Vicki L. *Cannery Women, Cannery Lives: Mexican Women, Unionization, and the California Food Processing Industry, 1930-1950* (1987).

Sanchez, George. *Becoming Mexican American: Ethnicity, Culture, and Identity in Chicano Los Angeles, 1900-1945*. New York: Oxford, 1993.

 Taylor, Quintard. *In Search of the Racial Frontier: African Americans in the American West, 1528-1990* (1998).

 ______. *The Forging of a Black Community: Seattle's Central District from 1870 through the Civil Rights Era* (1994).

 Van Nuys, Frank. *Americanizing the West: Race, Immigrants, and Citizenship, 1890-1930* (2002).

 Whitaker, Matthew C. *Race Work: The Rise of Civil Rights in the Urban West* (2005).
