---
title: "Reading List - Environmental History"
date: 2016-02-02
tags: [environmental history]
categories: [Readings]
---

# Surveys

Blackbourn, David. *The Conquest of Nature: Water, Landscape, and the Making of Modern Germany*. New York: W.W. Norton and Co., 2006.

Elvin, Mark. *The Retreat of the Elephants: An Environmental History of China*. New Haven: Yale University Press, 2004.

Flannery, Tim: *The Future Eaters: An Ecological History of the Australian Lands and Peoples*. New York: Brazilier, 1995.

Gadgil, M. and R. Guha. *This Fissured Land: An Ecological History of India*. Berkeley: University of California Press, 1993.

McCann, James. *Green Land, Brown Land, Black Land: An Environmental History of Africa, 1800-1990*. Portsmouth, NH: Heinemann, 1999.

McNeill, J.R. *Something New under the Sun: An Environmental History of the Twentieth-Century World*. New York: W.W. Norton, 2000.

Miller, Shawn William. *An Environmental History of Latin America*. Cambridge: Cambridge University Press, 2007.

Simmons, I.G. *An Environmental History of Great Britain: From 10,000 Years Ago to the Present*. Edinburgh: Edinburgh University Press, 2001.

Steinberg, Ted. *Down to Earth: Nature's Role in American History*. New York: Oxford University Press, 2002.

Wynn, Graeme. *Canada and Arctic North America: An Environmental History*. Santa Barbara: ABC-CLIO, 2007.

# Defining the Field

Braudel, Fernand. *The Mediterranean and the Mediterranean World in the Age of Phillip II*. Vol. 1. New York: Harper & Row, 1972.

Cronon, William, ed. *Uncommon Ground: Rethinking the Human Place in Nature*. New York: W.W. Norton, 1996.

Cronon, William. *A Place for Stories: Nature, History, and Narrative*. The Journal of American History 78, no. 4 (1992): 1347-1376.

Haraway, Donna. *Primate Visions: Gender, Race, and Nation in the World of Modern Science*. New York: Routledge, 1989.

Worster, Donald, ed. *The Ends of the Earth: Perspectives on Modern Environmental History*. Cambridge: Cambridge University Press, 1985.

MacEachern, Alan. "Voices Crying in the Wilderness: Recent Works in Canadian Environmental History." *Acadiensis* 31, no. 2 (2002): 215-26.

MacEachern, Alan and William J. Turkel, eds. *Method and Meaning in Canadian Environmental History*. Toronto: Nelson, 2009.

Melosi, M. V. "The Place of the City in Environmental History," Environmental History Review (Spring 1993): 1-23.

Merchant, Carolyn. "The Theoretical Structure of Ecological Revolutions." *Environmental Review* 11, no. 4 (1987): 265-74.

Nye, David E. "Technology, Nature, and American Origin Stories." *Environmental History* 8, no. 1 (2003): 8-25.

Parr, Joy "Notes for a More Sensuous History of Twentieth-Century Canada: The Timely, the Tacit, and the Material Body" *Canadian Historical Review*, 82(4) (2001), 720-45

Sörlin, Sverker, and Paul Warde. "The Problem of the Problem of Environmental History: A Re-Reading of the Field." *Environmental History*. 12.1 (2007): 107-130.

Taylor, Alan. "Unnatural Inequalities: Social and Environmental Histories." *Environmental History* 1 (1996): 6-19.

Taylor, Alan. "Wasty Ways: Stories of American Settlement." *Environmental History* 3 (1998): 291-310.

Flores, Dan. "Place: An Argument for Bioregional History." *Environmental History Review* 18, no. 4 (1994): 1-18.

Nash, Roderick. "The State of Environmenal History." In *The State of American History*, edited by Herbert J. Bass, 249-60. Chicago: Quadrangle Books, 1970.

Crosby, Alfred W. "The Past and Present of Environmental History." *American Historical Review* 100 (1995): 1177-89.

-----. "What's Next for Environmental History?" *Environmental History* 10 (1) 2005: 30-109.

Weiner, Douglas R. "A Death-Defying Attempt to Articulate a Coherent Definition of Environmental History" *Environmental History* 10 (3) 2005: 404-420.

Worster, Donald, et al. Articles in Special Issue, Journal of American History 76.4 (March 1990).

# Native Peoples and Environmental History

## General

Brody, Hugh. *The Other Side of Eden: Hunters, Farmers and the Shaping of the World*. Vancouver: Douglas & McIntyre, 2000.

Tyler, Mary Ellen. "Spiritual Stewardship in Aboriginal Resource Management Systems." *Environments* 22 (1993): 1-8.

## West Coast

Newell, Dianne. *Tangled Webs of History: Indians and the Law in Canada's Pacific Coast Fisheries*. Toronto: University of Toronto Press, 1997.

Harris, R. Cole. *Making Native Space: Colonialism, Resistance, and Reserves in British Columbia*. Vancouver: UBC Press, 2002.

Cruikshank, Julie. *Do Glaciers Listen? Local Knowledge, Colonial Encounters, and Social Imagination*. Vancouver & Seattle: UBC Press & University of Washington Press, 2005.

## Prairies

Binnema, Theodore. *Common and Contested Ground: A Human and Environmental History of the Northwestern Plains*. Norman: University of Oklahoma Press, 2001.

Carter, Sarah. *Lost Harvests: Prairie Indian Reserve Farmers and Government Policy*. Montreal: McGill-Queen's University Press, 1990.

Ens, Gerhard. *Homeland to Hinterland: The changing worlds of the Red River Metis in the Nineteenth Century*. Toronto: University of Toronto Press, 1996.

## Central

Trigger, Bruce G. *The Children of Aataentsic: A history of the Huron People to 1660*. Montreal: McGill-Queen's University Press, 1976.

White, Richard. *The Middle Ground: Indians, Empires, and Republics in the Great Lakes Region, 1650-1815*. Cambridge: Cambridge University Press, 1991.

## Boreal Forest and North

Dick, Lyle. *Muskox Land: Ellesmere Island in the Age of Contact*. Calgary: University of Calgary Press, 2001.

Tanner, Adrian. *Bringing Home Animals: Religious Ideology and Mode of Production of the Mistassini Cree Hunters*. London: C. Hurst, 1979.

Scott, Colin H. "Spirit and Practical Knowledge in the Person of the Bear among Wemindji Cree Hunters." *Ethnos* 71, no. 1 (2006): 51-66.

Sandlos, John. *Hunters at the Margin: Native People and Wildlife Conservation in the Northwest Territories*. Vancouver: UBC Press, 2007.

## East Coast

Wicken, William C. Mi'kmaq Treaties on Trial: History, land, and Donald Marshall Junior. Toronto: University of Toronto Press, 2002.

## Ecological Indian Debate:

Krech, Shepard. *The Ecological Indian: Myth and History*. New York: W.W. Norton, 1999.

Harkin, Michael Eugene, and David Rich Lewis. *Native Americans and the Environment: Perspectives on the Ecological Indian*. Lincoln: University of Nebraska Press, 2007.

Martin, Calvin. *Keepers of the Game: Indian-Animal Relationships and the Fur Trade*. Berkeley, Calif.: University of California Press, 1978.

Krech, Shepard, ed. *Indians, Animals, and the Fur Trade: A Critique of Keepers of the Game*. Athens: University of Georgia Press, 1981.

Carlson, Hans. "A Watershed of Words: Litigating and Negotiating Nature in James Bay, 1971-75." *Canadian Historical Review* 2004 85 (1): 63-84.

# Ecological Imperialism

Crosby, Alfred W. *Ecological Imperialism: The Biological Expansion of Europe, 900-1900*. Cambridge: Cambridge University Press, 1986.

Crosby, Alfred. *The Columbian Exchange: Biological and Cultural Consequences of 1492*. Westport, Connecticut: Greenwood, 1973.

Piper, Liza and John Sandlos, "A Broken Frontier: Ecological Imperialism in the Canadian North" *Environmental History* 12 (4) 2007: 759-795.

Dunlap, Thomas, "Remaking the Land: The Acclimatization Movement and Anglo Ideas of Nature" *Journal of World History* 8 (2) 1997: 303-319.

# Colonization and Early Settlement

Anderson, Virginia DeJohn. *Creatures of Empire: How Domestic Animals Transformed Early America*. Oxford: Oxford University Press, 2004.

Coates, Colin. *The Metamorphoses of Landscape and Community in Early Quebec*. Montreal: McGill-Queen's University Press, 2000.

Cook, Ramsay. "Cabbages Not Kings: Towards an Ecological Interpretation of Early Canadian History." *Journal of Canadian Studies* 25, no. 4 (1990-91): 5-16.

Cronon, William. *Changes in the Land: Indians, Colonists, and the Ecology of New England*. New York: Hill and Wang, 1983.

Forkey, Neil. *Shaping the Upper Canadian Frontier: Environment, Society, and Culture in the Trent Valley*. Calgary: University of Calgary Press, 2003.

Lower, Arthur. *Settlement and the Forest Frontier in Eastern Canada*. New York: Kraus Reprint, 1974 [reprint of 1936 edition].

Melville, Elinor. *A Plague of Sheep: Environmental Consequences of the Conquest of Mexico*. Cambridge: Cambridge University Press, 1994.

# Opening the West

Evans, Clinton L. The War on Weeds in the Prairie West: An environmental history. Calgary: University of Calgary Press, 2002.

Owram, Doug. Promise of Eden: The Canadian Expansionist Movement and the Idea of the West, 1856-1900. Toronto: University of Toronto Press, 1980.

Worster, Donald. Dust Bowl: The Southern Plains in the 1930s. New York: Oxford University Press, 1979.

Breen, David H. The Canadian Prairie West and the Ranching Frontier, 1874-1924. Toronto: University of Toronto Press, 1982.

Bunting, Robert. The Pacific Raincoast: Environment and Culture in an American Eden, 1778-1900. Lawrence: University Press of Kansas, 1997.

Sandwell, R.W., ed. Beyond the City Limits: Rural History in British Columbia. Vancouver: UBC Press, 1998.

Spry, Irene. "The Great Transformation: The Disappearance of the Commons in Western Canada." In Canadian Plains Studies 6: Man and Nature on the Prairies, edited by Richard Allen. Regina: Canadian Plains Research Center, 1976.

Worster, Donald. Rivers of Empire: Water, Aridity, and the Growth of the American West. New York: Pantheon Books, 1985.

# Fur Trade

Innis, Harold Adams. The Fur Trade in Canada : An Introduction to Canadian Economic History. Toronto: University of Toronto Press, 1999 [1930].

Ray, Arthur J. Indians in the Fur Trade: Their Role as Hunters, Trappers, and Middlemen in the Lands Southwest of Hudson Bay, 1660-1870. Toronto: University of Toronto Press, 1974.

Lutz, John. "After the Fur Trade: The Aboriginal Labouring Class of British Columbia, 1864-1890." Journal of the Canadian Historical Association 3 (1992): 69-93.

Warburton, Rennie and Stephen Scott. "The Fur Trade and Early Capitalist Development in British Columbia." Canadian Journal of Native Studies 5 (1985): 27-46.

# Fisheries

Cadigan, Sean. "Moral Economy of the Commons: Ecology and Equity in the Newfoundland Cod Fishery, 1815-1855." Labour/Le Travail 43 (Spring 1999): 9-42.

Taylor, Joseph E. Making Salmon: An Environmental History of the Northwest Fisheries Crisis. Seattle: University of Washington Press, 1999.

Ommer, Rosemary. ""One Hundred Years of Fisheries Crises in Newfoundland"." Acadiensis 23, no. 2 (1994): 5-20.

Boghue, Margaret Beattie. Fishing the Great Lakes: An Environmental History, 1783-1933. Madison: University of Wisconsin Press, 2000.

Newell, Diane and Rosemary Ommer, ed. Fishing Places, Fishing People: Traditions and Issues in Canadian Small-Scale Fisheries. Toronto: University of Toronto Press, 1998.

Pope, Peter Edward. Fish into Wine: the Newfoundland Plantation in the Seventeenth Century. Williamsburg, VA: University of North Carolina Press, 2004.

Harris, Douglas C. Fish, Law and Colonialism: The Legal Capture of Salmon in British Columbia. Toronto: University of Toronto Press, 2001.

Kurlansky, Mark. Cod: A Biography of the Fish That Changed the World. Toronto: A.A. Knopf Canada, 1997.

Taylor III, Joseph E. "The Historical Roots of the Canadian-American Salmon Wars." In Parallel Destinies: Canadian-American Relations West of the Rockies, edited by John M. Findlay and Ken S. Coates. Seattle: University of Washington Press, 2002.

Evenden, Matthew D. Fish Versus Power: An Environmental History of the Fraser River. New York: Cambridge University Press, 2004.

# Wildlife

Loo, Tina. States of Nature: Conserving Canada's Wildlife in the Twentieth Century. Vancouver: University of British Columbia Press, 2006.

Sandlos, John. Hunters at the Margin: Native People and Wildlife Conservation in the Northwest Territories. Vancouver: UBC Press, 2007.

Foster, Janet. Working for Wildlife: The Beginning of Preservation in Canada. Toronto: University of Toronto Press, 1998.

Colpitts, George. Game in the Garden: A Human History of Wildlife in Western Canada to 1940. Vancouver: UBC Press, 2002.

Dick, Lyle. Muskox Land: Ellesmere Island in the Age of Contact. Calgary: University of Calgary Press, 2001.

Dorsey, Kurkpatrick. The Dawn of Conservation Diplomacy: U.S.-Canadian Wildlife Protection Treaties in the Progressive Era. Seattle: University of Washington Press, 1998.

Hammond, Lorne. "Marketing Wildlife: The Hudson's Bay Company and the Pacific Northwest, 1821-1849." Forest and Conservation History 37 (1993): 14-25.

Isenberg, Andrew C. The Destruction of the Bison: An Environmental History. Cambridge: Cambridge University Press, 2000.

Jones, Karen. Wolf Mountains: A History of Wolves Along the Great Divide. Calgary: University of Calgary Press, 2002.

# Nature and Industry: Hydro-Electricity, Forestry, Mining

Josephson, Paul R. Industrialized Nature: Brute Force Technology and the Transformation of the Natural World. Washington: Island Press, 2002.

Nelles, H.V. The Politics of Development: Forests, Mines and Hydro-Electric Power in Ontario, 1849-1941. Toronto: Macmillan of Canada, 1974.

## Hydro-Electricity

Manore, Jean L. Cross-Currents: Hydroelectricity and the Engineering of Northern Ontario. Waterloo, ON: Wilfrid Laurier University Press, 1999.

Hornig, James F. Social and Environmental Impacts of the James Bay Hydroelectric Project. Montreal: McGill-Queen's University Press, 1999.

## Forestry

Langston, Nancy. Forest Dreams, Forest Nightmares: The Paradox of Old Growth in the Inland West. Seattle: University of Washington Press, 1995.

Rajala, Richard. Up Coast: Forests and Industry on British Columbia's North Coast, 1870-2005. Vancouver: UBC Press, 2006.

Wynn, Graeme. Timber Colony: A Historical Geography of Early Nineteenth Century New Brunswick. Toronto: University of Toronto Press, 1981.

Hak, Gordon. Turning Trees into Dollars: The British Columbia Coastal Lumber Industry, 1858-1913. Toronto: University of Toronto Press, 2000.

Rajala, Richard A. Clearcutting the Pacific Rain Forest: Production, Science, and Regulation. Vancouver: UBC Press, 1988.

Williams, Michael. Deforesting the Earth: From Prehistory to Global Crisis. Chicago: University of Chicago Press, 2003.

Hardy, René, and Normand Séguin. Forêt et société en Mauricie : la formation de la région de Trois-Rivières 1830-1930. Montréal, Ottawa: Boréal Express & Musée national de l'Homme du Canada, 1984.

Lower, Arthur. Great Britain's Woodyard: British America and the timber trade, 1763-1867. Montreal: McGill-Queen's University Press, 1973.

Flader, Susan. The Great Lakes Forest: An environmental and social history. Minneapolis: University of Minnesota Press & Forest History Society, 1983.

Gillis, R. Peter and Thomas R. Roach. 1986. Lost Initiatives: Canada's Forest Industries, Forest Policy, and Forest Conservation. New York: Greenwood.

Radforth, Ian. 1987. Bushworkers and Bosses: Logging in Northern Ontario, 1900-1980. Toronto: University of Toronto Press.
Swift, Jamie. 1983. Cut and Run: The Assault on Canada's Forests. Toronto: Between the Lines.

## Mining

Morse, Kathryn. The Nature of Gold: An Environmental History of the Klondike Gold Rush. Seattle: University of Washington Press, 2003.

Andrews,Thomas G. Killing for Coal: America's Deadliest Labor War. Cambridge, Mass: Harvard University Press, 2008.

LeCain,Timothy. "The Limits of Eco-Efficiency: Arsenic Pollution and the Cottrell Electrical Precipitator in U.S. Copper Mining." Environmental History 5(3) 2000: 336-351.

Isenberg, Andrew. Mining California: An Ecological History. New York: Hill & Wang, 2005.

Montrie, Chad. To Save the Land and People: A History of Opposition to Surface Coal Mining in Appalachia. Chapel Hill: University of North Carolina Press, 2003.

Rosner, David and Gerald Markowitz. Deadly Dust: Silicosis and the Politics of Occupational Disease in Twentieth-Century America. Princeton: Princeton University Press, 1991.

# Agriculture

## West Coast

Braun, Bruce. 2002. The Intemperate Rainforest: Nature, Culture, and Power on Canada's West Coast. Minneapolis and London: University of Minnesota Press.

Sandwell, R. W. Contesting Rural Space: Land policy and practices of resettlement on Saltspring Island, 1859-1891. Montreal: McGill-Queen's University Press, 2005.

## Prairies

Bantjes, Rod. Improved Earth: Prairie Space as Modern Artefact. Toronto: University of Toronto Press, 2005.

Breen, David. The Canadian Prairie West and the Ranching Frontier 1874-1924. Toronto: University of Toronto Press, 1983.

Cunfer, Geoff. On the Great Plains: Agriculture and Environment. Texas: Texas A&M University Press, 2005.

Danysk, Cecilia. Hired Hands: Labour and the development of prairie agriculture, 1880-1930. Toronto: McClelland & Stewart, 1995.

Dick, Lyle. Farmers Making Good: the development of Abernethy District, Saskatchewan, 1880-1920 2nd ed Calgary: University of Calgary Press, 2008.

Evans, Clinton. The War on Weeds in the Prairie West. Calgary: University of Calgary Press, 2002.

Jones, David C. Empire of Dust: Settling and abandoning the Prairie dry belt. Edmonton: University of Alberta Press, 1987.

Potyondi, Barry. In Palliser's Triangle: Living in the Grasslands, 1850-1930. Saskatoon: Purich Publishing, 1995.

Voisey, Paul L. Vulcan: The Making of a Prairie Community (Social History of Canada) Toronto: University of Toronto Press, 1988.

Wood, J. David. Places of Last Resort:The Expansion of the Farm Frontier into the Boreal Forest in Canada, c. 1910-1940. Montreal: McGill-Queen's University Press, 2006.

Donald Worster, Dust Bowl: The Southern Plains in the 1930s. New York : Oxford University Press, 1979.

## Ontario

Clarke, John. Land, Power and Economics on the Frontier of Upper Canada. Montreal: McGill-Queen's University Press, 2001.

Jones, Robert Leslie. History of Agriculture in Ontario, 1613-1880. Toronto: University of Toronto Press, 1946.

McCalla, Douglas. Planting the Province: The economic history of Upper Canada, 1784-1870. Toronto: University of Toronto Press, 1993.

McCallum, John. Unequal Beginnings: Agriculture and economic development in Quebec and Ontario until 1870. Toronto: University of Toronto Press, 1980.

Trigger, Bruce G. The Huron: Farmers of the North. New York: Holt Rinehart and Winston, 1969.

Wood, J. David. Making Ontario: Agricultural colonization and landscape recreation before the railroad. Montreal: McGill-Queen's University Press, 2000.

## Quebec

Courville, Serge. "La crise agricole du Bas-Canada, éléments d'une réflexion géographique (1e partie)." Cahiers de géographie du Québec 23, no. 62 (1980): 193-224.

---------. "La crise agricole du Bas-Canada, éléments d'une réflexion géographique (2e partie)." Cahiers de géographie du Québec 24, no. 63 (1980): 193-224.

Dechêne, Louise. Habitants et marchands de Montréal au XVIIe siécle. Paris: Plon, 1974.

Desbarats, Catherine. "Agriculture within the Seigneurial Régime of Eighteenth-Century Canada: Some thoughts on the recent literature." Canadian Historical Review 73, no. 1, March (1992): 1-29.

Greer, Allan. Peasant, Lord, and Merchant: Rural society in three Quebec parishes, 1740-1840. Toronto: University of Toronto Press, 1985.

Jones, Robert Leslie. "The Agricultural Development of Lower Canada, 1850-1867." Agricultural History 19, 4 (1945).

---------. "Agriculture in Lower Canada, 1792-1815." Canadian Historical Review 27 (1946).

---------. "French-Canadian Agriculture in the St. Lawrence Valley, 1815-1850." Agricultural History 16, 3 (1942).

Little, J. I. Crofters and Habitants: Settler society, economy, and culture in a Quebec township, 1848-1881. Montreal: McGill-Queen's University Press, 1991.

McInnis, R. M. "A Reconsideration of the State of Agriculture in Lower Canada in the First Half of the Nineteenth Century." Canadian Papers in Rural History III (1982): 9-49.

Ouellet, Fernand. Le Bas-Canada 1791-1840: changements structuraux et crise. Ottawa: Editions de l'Université d'Ottawa, 1976.

Séguin, Maurice. La "nation canadienne" et l'agriculture (1760-1850): essai d'histoire économique. Trois-Rivières: Éditions Boréal express, 1970.

Séguin, Normand. La conquête du sol au 19e siècle. Québec: Editions du Boréal Express, 1977.

---------, ed. Agriculture et colonisation au Québec: aspects historiques. Montréal: Boréal Express, 1980.

## East Coast

Anderson, Virginia DeJohn. Creatures of Empire: How domestic animals transformed early America. Oxford: Oxford University Press, 2004.

Donahue, Brian. The Great Meadow: Farmers and the land in colonial Concord. New Haven: Yale University Press, 2004.

Fiege, Mark. Irrigated Eden: The making of an agricultural landscape in the American West. Seattle: University of Washington Press, 1999.

Fitzgerald, Deborah. Every Farm a Factory: The Industrial Ideal in American Agriculture. New Haven: Yale University Press, 2003.

Worster, Donald. Dust Bowl: The southern plains in the 1930s. New York: Oxford University Press, 1979.

---------. Rivers of Empire: Water, aridity, and the growth of the American West. 1st ed. New York: Pantheon Books, 1985.

Stoll, Steven. Larding the Lean Earth: Soil and society in nineteenth-century America. 1st ed. New York: Hill and Wang, 2002.

Webb, Walter Prescott. The Great Plains. Boston: Ginn and company, 1931.

# Water

Benidickson, Jamie. The Culture of Flushing: A Social and Legal History of Sewage. Vancouver: UBC Press, 2007.

Bocking, Stephen. "Constructing Urban Expertise: Professional and Political Authority in Toronto, 1940-1970" Journal of Urban History 2006 33(1): 51-76.

Cioc, Mark. The Rhine: An Eco-Biography, 1815-2000. Seattle: University of Washington Press, 2002.

Colten, Craig. "Groundwater and the Law: Records v. Recollections" The Public Historian 20, no. 2 (1998): 25-44.

Goodman, Tristan M., "The Development of Prairie Canada's Water Law, 1870-1940" in Laws and Societies in the Canadian Prairie West, 1670-1940, ed. Louis A. Knafla and Jonathan Swainger (UBC Press, 2005): 266-279.

Kandel, Robert. Water from Heaven: The Story of Water from the Big Bang to the Rise of Civilization, and Beyond. New York: Columbia University Press, 2003.

Mauch, Christof, and Thomas Zeller. Rivers in History: Perspectives on Waterways in Europe and North America. Pittsburgh: University of Pittsburgh Press, 2008.

Wescoat, James L. Jr. and Gilbert F. White, Water for Life: Water Management and Environmental Policy Cambridge: Cambridge University Press, 2003.

White, Richard. The Organic Machine: The Remaking of the Columbia River. New York: Hill and Wang, 1995.

Worster, Donald. Rivers of Empire: Water, Aridity, and the Growth of the American West. New York: Pantheon, 1985

Bolster, Jeffrey W. Putting the Ocean in Atlantic History: Maritime Communities and Marine Ecology in the Northwest Atlantic, 1500-1800. American Historical Review 2008 113 (1): 19-47.

# The Conservation Movement

Nash, Roderick. Wilderness and the American Mind. 4th ed. New Haven: Yale University Press, 2001.

Sutter, Paul S. Driven Wild: How the Fight against Automobiles Launched the Modern Wilderness Movement. Seattle: University of Washington Press, 2002.

Jacoby, Karl. Crimes against Nature: Squatters, Poachers, Thieves, and the Hidden History of American Conservation. Berkeley: University of California Press, 2001.

Hays, Samuel. Conservation and the Gospel of Efficiency: The Progressive Conservation Movement. Cambridge, Mass: Harvard University Press, 1959.

Jasen, Patricia. Wild Things: Nature, Culture, and Tourism in Ontario, 1790-1914. Toronto: University of Toronto Press, 1995.

Worster, Donald. "Wild, Tame, and Free: Comparing Canadian and U.S. Views of Nature." In Parallel Destinies: Canadian-American Relations West of the Rockies, edited by John M. Findlay and Ken S. Coates. Seattle: University of Washington Press, 2002.

Dunlap, Thomas, Nature and the English Diaspora: Environment and History in the United States, Canada, Australia, and New Zealand New York: Cambridge University Press, 1999.

# Parks

Williams, Raymond. The Country and the City. London: Hogath Press, 1985.

## National, State, and Provincial Parks

Runte, Alfred. National Parks: The American Experience. 3rd ed. Lincoln: University of Nebraska Press, 1997.

MacEachern, Alan. Natural Selections: Natural Parks in Atlantic Canada, 1935-1970. Montreal: McGill-Queen's University Press, 2001.

Killan, Gerald. Protected Places: A History of Ontario's Provincial Park System. Toronto: Dundurn Press, 1993.

Brown, Robert Craig. "The Doctrine of Usefulness: Natural Resources and National Park Policy in Canada, 1887-1914." In The Canadian National Parks Today and Tomorrow, edited by J.G. Nelson and R.C. Scace, 94-110. Calgary: National and Provincial Parks Association of Canada and the University of Calgary, 1969.

Sellars, Richard West. Preserving Nature in the National Parks: A History. New haven: Yale University Press, 1997.

Catton, Theodore. National Park, City Playground: Mount Rainier in the Twentieth Century. Seattle: University of Washington Press, 2006.

Louter, David. Windshield Wilderness: Cars, Roads, and Nature in Washington's National Parks. Seattle: University of Washington Press, 2006.

MacLaren, I.S., ed. Culturing Wilderness in Jasper National Park: Studies in Two Centuries of Human History in the Upper Athabasca River Watershed. Edmonton: University of Alberta Press, 2007.

Bella, Leslie. Parks for Profit. Montreal: Harvest House,1987.

## Urban Parks

Rosenzweig, Roy and Elizabeth Blackmar. The Park and the People: A History of Central Park. Ithaca: Cornell University Press, 1992.

Chadwick, George F. The Park and the Town: Public Landscape in the 19th and 20th Centuries. London: London Architectural Press, 1966.

McDonald, Robert A.J. ""'Holy Retreat' or 'Practical Breathing Spot'?: Class Perceptions of Vancouver's Stanley Park, 1910-1913"." Canadiain Historical Review 45, no. 2 (1984): 127-53.

Young, Terrence. Building San Fransisco's Parks, 1850-1930. Baltimore: Johns Hopkins University Press, 2004.

Cranz, Galen. The Politics of Park Design: A History of Urban Parks in America. Cambridge: MIT Press, 1982.

Schuyler, David. The New Urban Landscape: The Redefinition of City Form in Nineteenth-Century America. Baltimore: Johns Hopkins Press, 1986.

# Landscapes

Taylor, C.J. Negotiating the Past: The Making of Canada's National Historic Parks and Sites. Montreal: McGill-Queen's University Press, 1990.

Schama, Simon. Landscape and Memory. New York: Alfred A. Knopf, Inc., 1995.

Coates, Colin M. The Metamorphoses of Landscape and Community in Early Quebec. Montreal: McGill-Queen's University Press, 2000.

Alanen, Arnold R. and Robert Z. Melnick. Preserving Cultural Landscapes in America. Baltimore: John Hopkins University Press, 2000.

Jackson, John Brinckerhoff. Discovering the Vernacular Landscape. New Haven: Yale University Press, 1984.

Mckay, Ian. "History and the Tourist Gaze: The Politics of Commemoration in Nova Scotia, 1935-1964." Acadiensis 22, no. 2 (1993): 102-38.

Campbell, Claire. Shaped by the West Wind: Nature and History in Georgian Bay. Vancouver: UBC Press, 2005.

Rackham, Oliver. The History of the Countryside: The Classic History of Britain's Landscape, Flora and Fauna. London: Dent, 1986.

Stilgoe, John R. Common Landscape of America, 1580 to 1845. New Haven: Yale University Press, 1982.

Wood, J. David. Making Ontario: Agricultural Colonization and Landscape Re-creation before the Railway. Montreal and Kingston: McGill-Queen's University Press, 2000.

# "Disasters"

Castonguay, Stephane. "The Production of Flood as Natural Catastrophe: Extreme Events and the Construction of Vulnerability in the Drainage Basin of the St. Francis River (Quebec), Mid-Nineteenth to Mid-Twentieth Century." Environmental History 12, no. 4 (2007): 820-844.

Davis, Mike. Ecology of Fear: Los Angeles and the Imagination of Disaster. New York: Metropolitan Books, 1998.

Pyne, Stephen J. Fire in America: A Cultural History of Wildland and Rural Fire. Princeton: Princeton University Press, 1982.

Steinberg, Theodore. Acts of God: The Unnatural History of Natural Disaster in America. Oxford: Oxford University Press, 2000.

Sean Kheraj. "Restoring Nature: Ecology, Memory, and the Storm History of Vancouver's Stanley Park" Canadian Historical Review. 88 (4) 2007: 577-612.

O'Neill, Karen M. Rivers by Design: State Power and the Origins of U.S. Flood Control, Durham: Duke University Press, 2006.

Colten, Craig. An Unnatural Metropolis: Wresting New Orleans from Nature, Baton Rouge, 2006.

Orsi, Jared. Hazardous Metropolis: Flooding and Urban Ecology in Los Angeles, Berkeley, 2004.

Kelman, Ari. A River and Its City: The Nature of Landscape in New Orleans, Berkeley, 2003.

# Cities

Benidickson, Jamie. The Culture of Flushing: A Social and Legal History of Sewage. Vancouver: UBC Press, 2007.

Cronon, William. Nature's Metropolis: Chicago and the Great West. New York: W.W. Norton, 1991.

Dagenais, Michèle, and Caroline Durand. "Cleansing, Draining and Sanitizing the City: Conceptions and Uses of Water in the Montreal Region." The Canadian Historical Review 87, no. 4 (2006): 621-651.

Tarr, Joel A. The Search for the Ultimate Sink: Urban Pollution in Historical Perspective. Akron, Oh: University of Akron Press, 1996.

Melosi, Martin V. Effulent America: Cities, Industry, Energy, and the Environment. Pittsburgh: University of Pittsburgh Press, 2001.

Melosi, Martin V. The Sanitary City : Urban Infrastructure in America from Colonial Times to the Present. Baltimore: John Hopkins University Press, 2000.

Bouchier, Nancy B. and Cruikshank, Ken. "The War on the Squatters, 1920-1940: Hamilton's Boathouse Community and the Re-Creation of Recreation on Burlington Bay." Labour/Le Travail 51 (2003): 9-46.

Davis, Mike. Dead Cities: And Other Tales. New York: New Press, 2002.

Murphy, Raymond. "Extreme Weather and the Energy Metabolism of the City." Environment and History 8, no. 1 (2002): 43-64.

Gandy, Matthew. Concrete and Clay: Reworking Nature in New York City. Cambridge: MIT Press, 2003.

Klingle, Matthew. Emerald City: An Environmental History of Seattle. New Haven: Yale University Press, 2007. [@klingle2007emerald]()

Kelman, Ari. A River and Its City: The Nature of Landscape in New Orleans. Berkeley: University of California Press, 2003.

Colten, Craig. Unnatural Metropolis: Wresting New Orleans from Nature. Baton Rouge: Louisiana State University Press, 2005.

Walker, Richard. *The Country in the City: The Greening of the San Francisco Bay Area*. Seattle: University of Washington Press, 2008. [@walker2007countrycity]()

Special Issue of Urban History Review on Canadian Urban Environmental History. 34.1 (Fall 2005).

# Modern Environmentalism

Worster, Donald. Nature's Economy: A History of Ecological Ideas. Cambridge: Cambridge University Press, 1994.

Read, Jennifer. "'Let Us Heed the Voice of Youth': Laundry Detergents, Phosphates and the Emergence of the Environmental Movement in Ontario." Journal of the Canadian Historical Association 7 (1996): 227-50.

Carson, Rachel. Silent Spring. New York: Houghton Mifflin, 1962.

Merchant, Carolyn. Ecological Revolutions: Nature, Gender, and Science in New England. Chapter Hill: University of North Carolina Press, 1989.

Helvarg, David. The War against the Greens: The "Wise-Use" Movement, the New Right, and Anti-Environmental Violence. San Fransisco: Sierra Club Books, 1994.

Gottleib, Robert. Forcing the Spring: The Transformation of the American Environmental Movement. Washington, DC: Island Press, 1993.

Keeling, Arn and Robert McDonald. "The Profligate Province: Roderick Haig-Brown and the Modernizing of British Columbia." Journal of Canadian Studies 36 (2001): 7-23.

MacEachern, Alan. The Institute of Man and Resources: An Environmental Fable. Charlottetown: Island Studies Press, 2003.

Kilan, Gerald and George Warecki. "The Algonquin Wildlands League and the Emergence of Environmental Politics in Ontario, 1965-1975." Environmental History Review 16, no. 4 (1992): 1-28.

Wilson, Jeremy. Talk and Log: Wilderness Politics in British Columbia, 1965-1996. Vancouver: UBC Press, 1998.

# The State

Castonguay, Stephane. Naturalizing Federalism: Insect Outbreaks and the Centralization of Entomological Research in Canada, 1884-1914. Canadian Historical Review 85, no. 1 (2004): 1-35.

Castonguay, Stephane. Protection des cultures, construction de la nature: agriculture, foresterie et entomologie au Canada 1884-1959. Septentrion, Sillery (2004)

Girard, Michel F. L' Ecologisme Retrouve : Essor et Declin de la Commission de la Conservation du Canada. Ottawa: Presses de l'Universite d'Ottawa, 1994.

Scott, James. Seeing Like a State: Why Certain Schemes to Improve the Human Condition Have Failed. New Haven: Yale University Press, 1998.

Murton, James. Creating a Modern Countryside: Liberalism and Land Resettlement in British Columbia. Vancouver: UBC Press, 2007.

Loo, Tina. "People in the Way: Modernity, Environment, and Society on the Arrow Lakes." BC Studies 142-143 (Summer/Autumn 2004), 161-97.

# Environment and Social Equity

Cruikshank, Ken and Nancy B. Bouchier. "Blighted Areas and Obnoxious Industries: Constructing Environmental Inequality on an Industrial Waterfront, Hamilton, Ontario, 1890-1960." Environmental History 9, no. 3 (2004): 464-96.

Bullard, Robert. Dumping in Dixie: Race, Class and Environmental Quality.

Flanagan, M.A. "The City Profitable, the City Livable: Environmental Policy, Gender, and Power in Chicago in the 1910s," Journal of Urban History 22 (Jan. 1996): 163-190.

Hurley, A. Environmental Inequalities: Class, Race, and Industrial Pollution in Gary, Indiana, 1945-1980 (Chapel Hill, NC, 1995).

Melosi, M.V. "Equity, Eco-racism and Environmental History," Environmental History Review 19 (Fall 1995): 1-16.

Rosen, C.M. "Noisome, Noxious, and Offensive Vapors, Fumes and Stenches in American Towns and Cities, 1840-1865," Historical Geography 25 (1997): 49-82.

Loo, Tina. "Disturbing the Peace: Environmental Change and the Scales of Justice on a Northern River." Environmental History 12 (October 2007): 895-919.

Wirth, John D. "The Trail Smelter Dispute: Canadians and Americans Confront Transboundary Pollution, 1927-41." Environmental History 1, no. 2 (1996): 34-51.

Scharff, Virginia J. (Ed.). 2003. Seeing Nature through Gender. Lawrence, Kansas: University Press of Kansas.

Novotny, Patrick. 2000. Where We Live, Work and Play: The Environmental Justice Movement and the Struggle for a New Environmentalism;

Platt, Harold L. Shock Cities: The Environmental Transformation and Reform of Manchester and Chicago. Chicago: University of Chicago Press, 2005.

Praeger Series in Transformational Politics and Political Science. Westport, CT: Praeger.

Pulido, Laura, and Devon Gerardo Pena. 1998. Environmentalism and Positionality: The Early Pesticide Campaign of the United Farm Workers' Organizing Committee, 1965-1971. Race, Gender & Class 6 (1):33-.

Taylor, Dorceta E. 1997. American Environmentalism: The Role of Race, Class, and Gender in Shaping Activism 1820-1995. Race, Gender & Class 5 (1):16-62.

Gugliotta, Angela. 2000. Class, Gender, and Coal Smoke: Gender Ideology and Environmental Injustice in Pittsburgh, 1868-1914. Environmental History 5 (2):165-193.

Platt, Harold L. 2000. Jane Addams and the Ward Boss Revisited: Class, Politics, and Public Health in Chicago, 1890-1930. Environmental History 5 (2):194-222.

Pulido, Laura. 1996. Environmentalism and economic justice: two Chicano struggles in the Southwest, Society, environment, and place. Tucson: University of Arizona Press.

LaDuke, Winona. 1999. All Our Relations: Native Struggles for Land and Life. Boston: South End Press.

# Science, Technology, and the Environment

Bess, Michael. The Light-Green Society: Ecology and Technological Modernity in France, 1960- 2000. Chicago: University of Chicago Press, 2003.

Dunlap, Thomas. DDT: Scientists, Citizens, and Public Policy. Princeton: Princeton University Press, 1981.

Jasanoff, Shiela. Designs on Nature: Science and Democracy in Europe and the United States. Princeton: Princeton University Press, 2005.

Marx, Leo. The Machine in the Garden: Technology and the Pastoral Ideal in America. New York: Oxford University Press, 1967.

Merchant, Carolyn. Ecological Revolutions: Nature, Gender, and Science in New England. Chapel Hill: The University of North Carolina Press, 1989.

Nash, Linda. Inescapable Ecologies: A History of Environment, Disease, and Knowledge. Berkley: University of California Press, 2006.

Nye, David E. American Technological Sublime. Cambridge: MIT Press, 1994.
