---
title: "Reading List - Latin America"
date: 2016-02-02
tags: [Latin America, Mexico, revolution]
categories: [Readings]
---

Jason A. Heppler  
University of Nebraska -- Department of History  
Readings List -- Latin America  
Advisor: Prof. Doug Seefeldt

## I. Mexican Revolution

Alonso, Ana María. *Thread of Blood: Colonialism, Revolution, and Gender on Mexico's Northern Frontier*. Tucson: University of Arizona Press, 1995.

Anderson, Benedict. *Imagined Communities: Reflections on the Origin and Spread of Nationalism*. Verso, 2006.

Baily, Samuel L., Ronn Pineo, and James Baer. *Cities of Hope: People, Protests, and Progress in Urbanizing Latin America, 1870-1930*. Westview Press, 2000.

Bantjes, Adrian, et al. *The Eagle and the Virgin: Nation and Cultural Revolution in Mexico, 1920-1940*. Duke University Press, 2005.

Beatty, Edward. *Institutions and Investment: The Political Basis of Industrialization in Mexico before 1911*. Stanford: Stanford University Press, 2001.

Becker, Marjorie. *Setting the Virgin on Fire: Lázaro Cárdenas, Michoacán Peasants, and the Redemption of the Mexican Revolution*. Berkeley: University of California Press, 1995.

Beezley, William H. *Mexican National Identity: Memory, Innuendo, and Popular Culture*. Tucson: University of Arizona Press, 2008.

Benjamin, Thomas. *La Revolución: Mexico's Great Revolution as Memory, Myth, and History*. Austin: University of Texas Press, 2000.

Bliss, Katherine. *Compromised Positions: Prostitution, Public Health, and Gender Politics in Revolutionary Mexico City*.

Bortz, Jeff, and Stephen Haber. *The Mexican Economy, 1870-1930: Essays on the Economic History of Institutions, Revolution, and Growth*. Stanford: Stanford University Press, 2002.

Brenner, Anita. *The Wind that Swept Mexico: The History of the Mexican Revolution 1910-1942*. University of Texas Press, 1989.

Coatsworth, John. *Growth against Development: The Economic Impact of Railroads in Porfirian Mexico*. DeKalb: Northern Illinois University Press, 1981.

Dawson, Alexander. *Indian and Nation in Revolutionary Mexico*. Tucson: University of Arizona Press, 2004.

French, William E. *A Peaceful and Working People: Manners, Morals, and Class Formation in Northern Mexico*. Albuquerque: University of New Mexico Press, 1996.

Gill, Anthony. *Rendering unto Caesar: The Catholic Church and the State in Latin America*. University of Chicago Press, 1998.

Gilly, Adolfo. *The Mexican Revolution: A People's History*. New Press, 2006.

Gonzales, Luis. *San José de Gracia: Mexican Village in Transition*.

Gonzales, Michael. *The Mexican Revolution, 1910-1940*. University of New Mexico Press, 2002.

Guardino, Peter. *Peasants, Politics, and the Formation of Mexico's National State: Guerro, 1800-1857*. Stanford University Press, 2002.

Haber, Stephen. *Industry and Underdevelopment: The Industrialization of Mexico, 1890-1940*. Stanford: Stanford University Press, 1989.

Hamnett, Brian. *Roots of Insurgency: Mexican Regions, 1750-1824*. New York: Cambridge, 1986.

Hall, Linda, and Don Coerver. *Revolution on the Border: The United States and Mexico, 1910-1920*. Albuquerque: University of New Mexico Press, 1988.

Hart, John Mason. *Revolutionary Mexico: The Coming and Process of the Mexican Revolution*. University of California Press, 1997.

Knight, Alan. *The Mexican Revolution*. Cambridge: Cambridge University Press, 1986.

Knight, Alan. "The Mexican Revolution: Bourgeois? Nationalist? Or Just a 'Great Rebellion'?" *Bulletin of Latin American Research*, vol. 4 no. 2 (1985): 1-37.

LaFrance, David G. *Revolution in Mexico's Heartland: Politics, War, and State Building in Puebla, 1913-1920*. Wilmington: SR Books, 2003.

MacLachlan, Colin M. *The Forging of the Cosmic Race: A Reinterpretation of Colonial Mexico*. Berkeley: University of California Press, 1980.

MacLachlan, Colin M. *Anarchism and the Mexican Revolution: The Political Trials of Ricardo Flores Magón in the United States*. Berkeley: University of California Press, 1991.

Piccato, Pablo. *City of Suspects: Crime in Mexico City, 1900-1931*.

Ruiz, Ramon. *Great Rebellion Mexico, 1905-1924*. Norton, 1980.

Sandos, James. *Rebellion in the Borderlands: Anarchism and the Plan of San Diego, 1904-1923*. Norman: University of Oklahoma Press, 1992.

Tinker Salas, Miguel. *In the Shadow of the Eagles: Sonora and the Transformation of the Border During the Porfiriato*. Berkeley: University of California Press, 1997.

Tutino, John. *From Insurrection to Revolution in Mexico: Social Basis of Agrarian Violence, 1750-1940*. Princeton University Press, 1989.

Vanderwood, Paul. *The Power of God Against the Guns of Government: Religious Upheaval in Mexico at the Turn of the Nineteenth Century*. Stanford University Press, 1998.

Vaughan, Mary Kay. *Cultural Politics in Revolution: Teachers, Peasants, and Schools in Mexico, 1930-1940*. Tucson: University of Arizona Press, 1997.

Wasserman, Mark. *Capitalists, Caciques, and Revolution: The Native Elite and Foreign Enterprise in Chihuaua, Mexico, 1854-1911*. Chapel Hill: University of North Carolina Press, 1984.

Weiner, Richard. *Race, Nation, and Market: Economic Culture in Porfirian Mexico*. Tucson: University of Arizona Press, 2004.

Wells, Allen and G. M. Joseph. *Summer of Discontent, Seasons of Upheaval: Elite Politics and Rural Insurgency in Yucatan, 1976-1915*. Stanford: Stanford University Press, 1996.

Womack, John. *Zapata and the Mexican Revolution*. Knopf, 1969.

## II. Land and Agrarian Reform

Boyer, Christopher. *Becoming Campesinos: Politics, Identity, and Agrarian Struggle in Postrevolutionary Michoacán, 1920-1935*. Stanford: Stanford University Press, 2003.

___. "Old Loves, New Loyalties: Agrarismo in Michoacán, 1920-1928." *Hispanic American Historical Review* vol. 78 no. 3 (August 1998): 419-455.

Coatsworth, John. "Railroads, Landholding, and Agrarian Protest in the Early Porfiriato." *Hispanic American Historical Review* vol. 54 no. 1 (February 1974): 48-71.

Coatsworth, John, Alan Knight, Jane-Dale Lloyd, Michael Kearney, Terri Koreck, Ana Alonso, et al. *Rural Revolt in Mexico: US Intervention and the Domain of Subaltern Politics*. Duke University Press, 1998.

Cotter, Joseph. *Troubled Harvest: Agronomy and Revolution in Mexico, 1880-2002*. Praeger Publishers, 2003

Esteva, Gustavo. *The Struggle for Rural Mexico*. South Hadley, Mass: Bergin and Garvey, 1983.

Hall, Linda B. "Alvaro Obregón and the Politics of Mexican Land Reform, 1920-1924." *Hispanic American Historical Review*, vol. 60 no. 2 (May 1980): 213-238.

Harvey, Neil. *The Chiapas Rebellion: The Struggle for Land and Democracy*. Duke University Press, 1998.

Jacobs, Ian. *Ranchero Revolt: The Mexican Revolution in Guerrero*. Austin: University of Texas Press, 1982.

Katz, Friedrick, ed. *Riot, Rebellion, and Revolution: Rural Social Conflict in Mexico*. Princeton: Princeton University Press, 1988.

Markiewicz, Dana. *The Mexican Revolution and the Limits of Agrarian Reform, 1915-1946*. Boulder: Lynne Rienner, 1993.

Purnell, Jennie. *Popular Movements and State Formation in Revolutionary Mexico: The Agraristas and Cristeros of Michoacán*. Duke University Press, 1999.

Randall, Laura. *Reforming Mexico's Agrarian Reform*. ME Sharpe, 1996.

Ronfeldt, David. *Atencingo: The Politics of Agrarian Struggle in a Mexican Ejido*. Stanford: Stanford University Press, 1973.

Sanderson, Steven. *Agrarian Populism and the Mexican State: The Struggle for Land in Sonora*. Berkeley: University of California Press, 1981.

Schneider, David. *Agrarian Revolt in a Mexican Village*. Englewood Cliffs, NJ: Prentice Hall, 1970.

Stevens, Donald. "Agrarian Policy and Instability in Porfirian Mexico." *The Americas* vol. 39 no. 2 (October 1982): 153-166.

Tannenbaum, Frank. *The Mexican Agrarian Revolution*. New York: Macmillan, 1929.

Tutino, John. *From Insurrection to Revolution in Mexico: Social Bases of Agrarian Violence in Mexico, 1750-1940*. Princeton: Princeton University Press, 1986.

Walker, David. "Homegrown Revolution: The Hacienda Santa Catalina del Alamo y Anexas and Agrarian Protest in Eastern Durango, Mexico, 1897-1913." *Hispanic American Historical Review* vol. 72 no. 2 (May 1992): 239-273.
