---
title: "San Jose Water Company"
date: 2016-04-05
tags: [San Jose, San Jose Water Company, water, dissertation]
categories: [Research]
project: machinesvalley
---

### Timeline

Date        Note
----        ----
1854        First artesian well was dug in San Jose, providing a safe supply of potable water.
1865        Donald McKenzie, local foundry owner, acquires the rights to provide water to the residents of San Jose and Santa Clara. Realizing that delivery of water offered a business opportunity, he builds two water tanks at San Jose Foundry.
1866        San Jose Water Company is formed and incorporated in November by Donald McKenzie, John Bonner & Anthony Cabot to serve Santa Clara and San Jose.
1868        San Jose Water was reincorporated and its capitol stock increased to $300,000. The extra funds needed to build the company's first reservoirs.
1869        Nathaniel Mason, McKenzie's replacement as company president oversees the building of Seven-Mile Reservoir, the company's first.
1870        Seven-Mile Reservoir is completed.
1871        Three-Mile Reservoir is completed. Tisdale Reservoir, joint venture with the Los Gatos Manufacturing Company is completed. Los Gatos Manufacturing Company, a flour mill who had already built dams and reservoirs for it's own business, workes closely with San Jose Water Company until 1886.
1874        Edward Williams becomes company President, a post he holds until 1900 except for a two year period from 1894-1896 when William Tisdale holds the job.
1886        Los Gatos Manufacturing Company buys Los Gatos Water Company.
1890        San Jose Water Company purchases Los Gatos Manufacturing Company ending the rivelry and adding Los Gatos customers.
1874-1879	  San Jose Water expands steadily. Opens a pair of reservoirs, Lake McKenzie and Lake Kittredge, during the late 1870's.
1882        Lake Cozzens opens.
1885        Lake Williams Reservoir opens under Tisdale's watch.
1895        San Jose Water Company loses Santa Clara business when the community elects to build a municipal water works.
1899        Edward Williams returns as president of the company and acquires Mountain Springs Water Company.
1900-1907   George W. Cozzens succeeds Williams as company president and continues a policy of buying land along the Los Gatos Creek.
1903-1905   Coyote Creek and other streams feed artesian belt that surrounds San Jose. In 1903, San Jose Water begins digging wells to tap into this supply for additional water. Another company, Bay Cities Water Company, hoping to siphon off 80 million gallons a day for sale to it's San Francisco and Oakland customers, buys 1500 acres of land in the Coyote Creek watershed. San Jose Water Company and the valley ranchers oppose the purchase and began a two year court battle that they finally win in 1905.
1907        George McKee becomes president. Under his watch the company adds nine wells and two pumping stations.
1912        Joseph Ryland becomes president. Serves from 1912-1928.
1916        50 year charter expires. San Jose Water Works is created, taking over all the franchises controlled by San Jose Water Company and picking up additional water rights along Los Gatos Creek from PG&E.
1919        Acquires Cottage Grove Water Works and Cherryhurst Water Company.
1928        Acquires Willow Glen Water Works. San Jose Water Company now serves 23,000 customers.
1929        General Water Works and Electric Company bought controlling interest in San Jose Water but management remained unchanged. Major effort during the next decade is to replace aging wooden flume that connected Los Gatos Creek to Jones Dam.
1936        San Jose Water company purchases the entire town of Wrights located in the Santa Cruz mountains.
1937        San Jose Water hires Ralph Elsman as president. He holds the job longer than anone else, serving 31 years until 1968.
1945        San Jose Water gained its financial independence from General Water and is placed on a more staple financial footing by reorganizing the company and taking it public. Elsman also spends $60 million in capital improvements.
1951        Austrian Dam built - providing much of the additional storage capacity needed for the tremendous economic growth in the Santa Clara Valley.
1960s       Company begins drawing on water imported to the valley to supplement supplies.
1965        Computerized operations system was installed to monitor water levels and make optium use of pumps.
1968        Nathaniel Kendall, succeeds Ralph Elsman as president of San Jose Water Company.
1974        J. W. Weinhardt becomes president.
1976-1977   During the drought period, Weinhardt institutes a water conservation program, distributing kits to customers that included showerhead flow restrictors, toilet displacement bottles and dye tablets to detect leaks. The program showed immediate positive results. The company also improves the company's customer service capabilities. The aging distribution infrastructure is upgraded.
1980        Campbell Water Company is acquired adding 5,300 customers to the 190,000 customers already served by San Jose Water.
1983        Company changes its name from San Jose Water Works to San Jose Water Company.
1985        Company shareholders create a holding company called SJW Corporation. In July, SJW acquied San Jose Water in a stock exchange with the stock of the holding company now trading on the American Stock Exchange in place of San Jose Water. In October SJW created SJW Land Company.
1997        San Jose Water takes over operation of the City of Cupertino's water system under the terms of a 25 year lease. By the end of the decade, the company served more than 970,00 customers.
1999-2001	American Water Works, a New Jersey based company, offers $390 million for San Jose Water. By 2001, frustrated that the acquisition has not gained approval from California PUC, American Water Works walks away from the deal.
1999        Weinhardt steps down as CEO, remains as chairman. W. Richard Roth replaces him as CEO.
2001        Crystal Choice Water Service is launched. It offered San Jose Water customers a chance to rent or purchase Kinetico's total home water treatment system, which combined in a single unit chlorine removal, water softening and a reverse osmosis process to produce drinking water.
2002        Weinhardt retires as chairman and is succeeded by Drew Gibson.

