---
title: "segelheer2010visualization"
date: 2016-02-04
tags: [data visualization, narrative, reading notes]
categories: [Readings]
project: visualization-humanities
---

<http://vis.stanford.edu/files/2010-Narrative-InfoVis.pdf>

p. 1139: Proposing the term "data stories," which differ from stories in text and film with "a set of events in a tightly controlled progression." Stories with data can "be interactive, inviting verification, new questions, and alternative explanations."

p. 1139: Outline seven genres of narrative visualization: magazine style, 
annotated chart, partitioned poster, flow chart, comic strip, slide show, and 
video.

p. 1147: 

> As our understanding of narrative visualization improves, it also opens up 
> new opportunities for visualization tool research. How should we extend 
> visual analysis applications to enable storytelling Interfaces that combine 
> visualization construction with the specification of narrative structure, 
> textual/graphical annotation, visual highlighting techniques, transitions, 
> and interactive controls could have a transformative impact on the medium, 
> so long as they can be used by data domain experts, not just technology 
> experts.
