---
title: self2003babylon
date: 2015-07-21
tags: [reading notes, African Americans, Oakland, East Bay, civil rights, spatial history]
categories: [Readings]
project: machinesvalley
---

Self asserts the most significant political, economic and spatial change
in postwar America was the "overdevelopment of suburbs and the
underdevelopment of cities." (p. 1), and between 1945 and 1970 protracted
social and political struggles "over land, taxes, jobs, and public
policy" gave rise to black power politics and neopopulist conservativism
among whites. Centering his analysis on Oakland, California, self writes
that African Americans saw the city as a colony exploited by the suburb
while simultaneously white homeowners monopolized and segregated postwar
prosperity. (p. 1)

Contests over local politics became "contests over the nature and
expression of the American welfare state." (p. 3) Self's book, then,
examines contests over the distribution of postwar prosperity in Oakland
between 1940 and 1970 (transition from an era of possibility to an era
of limits?). The contest had wider relevance to California politics
regarding the distribution of assets of postwar affluence and the
triumph of liberalism and the inequalities it created and were left
unresolved, the promises of the welfare state and the backlash of the
tax revolt.

> Oakland and the East Bay thus incubated two of California's most important postwar political traditions: a broad liberal one that sought expansions of the social wage and racial equality; and an equally broad populist-conservative one that celebrated private rights and understood liberalism's limits through property and homeownership. (p. 7)

The work is divided into three parts:

* Part 1: Traces "visions of the postwar city--those of urban trade
  unionists, African American leaders and activists, and
first-generation suburbanites--and the contests to realize those
visions." (p. 8).
    * Political and spatial identities sought "class harmony in pastoral
      cities where factories and homes existed in unobtrusive balance;
	  home-owner democracy in both city and suburb, literally "*home* rule" in
	  the words of one suburbanite; and an endless horizon of upward social
	  mobility with a plentiful supply of good jobs and inexpensive new
	  homes." (p. 8)
* Part 2: Examining "Oakland planners, developers, and capitalists
  turning to the instruments and technologies of postwar urban design to
remake their city." (p. 9)
* Part 3: The story's "denouement comes in a series of revolts and
  restorations." (p. 9)
    * African Americans "articulated a radical critique of the whole of
      metropolitan development since World War II and implicated
liberalism in continued black poverty." (p. 10)
    * "Homeowners embraced tax reform for an enormous variety of
      reasons, but they nonetheless produced a dramatic convergence of
political ideology around an antistatist, property-owning
individualism." (p. 10)

The book combines political culture ("how political contest is shaped,
framed, and understood" (p. 10)) and metropolitan space ("how and where
urbanization creates markets, property, and communities" (p. 10)). The
book examines the convergence of black political struggles and the
politics of suburban city building. Mapping "how capital and politics
create space" (p. 16) tells the story of politics and political culture
intertwined with the modernization of urban space (p. 17).

Oakland embodies the contradictions of postwar American metropolises:
poverty among wealth, racial apartheid at the heart of liberalism, high
unemployment during economic growth (p. 20).

## White Flight

Self shies away from "white flight" as a useful metaphor arguing that it
"shifts focus away from the complicated political production of suburban
communities in place. Furthermore, it fails to capture the essential
political-economic issue in suburban development: taxation and its
relationship to the provisioning of a welfare state." (p. 2) Instead of
seeing "white flight" and "black power" as separate stories, he tells
them together to illustrate metropolitanization's centrality to postwar
US history.

Aaron Cavin's dissertation likewise rejects "white flight" as a metaphor to explain
postwar suburban politics. See [cavin2012](/cavin2012/).

## Space

Self uses space as an analytical framework, identifying three
overlapping categories in Oakland (p. 17):

1. space as property
2. space as social imagination
3. space as political scale

> Space offers an important context to the story of Oakland, the East Bay, and the nation: "People, communities, and institutions did not compete for resources for abstract goals and purposes. They competed to put those resources to use to create particular and concrete places. We cannot separate historical actors from their spatial relationships.  Class and race are lived through the fabric of urban life and space.  Civil rights, black power, and tax reform political movements did not call for rights in abstract terms and ill-defined places. They called for very specific things in relation to very specific places. (p. 17)

Space offers important elements to the story:

1. The build environment of offices, factories, neighborhoods, parks,
and schools. These are physical markers of a place, but also serve as a
form of capital ("capitalism drives the creation of fixed spaces" (p.
18)). Capitalism in a place creates pressures to abandon existing cities
or remake them, causing tensions of development and redevelopment.
2. Property as a space that produces capital. Corporate city limits,
racial red lines, zoning codes, and highway right of way are the
"grammar of local development" and a tension exists over the role of
property in civic life, the distribution of tax burdens, and the buying
and selling of property. Space, however, is more than just property:
they extend beyond the marketplace and structure interactions regarding
the organization of politics or the police relationship with
neighborhoods containing schools. Struggles over space are struggles
over the power to "control and organize space and the leverage to wring
opportunity out of the American industrial metropolis during its
disruptive postwar cycles of development and redevelopment." (p. 18)
3. Space serves as a social imagination. On the one hand, Oakland was
considered an "industrial garden" by developers and boosters. African
Americans came to see the garden as a "plantation." (p. 18-19)
4. Space organizes political scale. Electoral politics ripples out from
the household, to neighborhood, to district, to city, to county, to
state, and to the federal government. Postwar suburban history contends
with local political arenas on the one hand and the enormous power of
the federal government on the other. (p. 19)
